-- CreateTable
CREATE TABLE "Game" (
    "ID_GAME" TEXT NOT NULL,
    "ID_PLAYER_1" INTEGER NOT NULL,
    "ID_PLAYER_2" INTEGER NOT NULL,
    "WINNER" INTEGER NOT NULL,
    "TURNS" TEXT NOT NULL,

    CONSTRAINT "Game_pkey" PRIMARY KEY ("ID_GAME")
);

-- CreateTable
CREATE TABLE "News" (
    "ID_NEWS" INTEGER NOT NULL,
    "ID_PLAYER" INTEGER NOT NULL,
    "TEXT" TEXT NOT NULL,
    "TITLE" TEXT NOT NULL,
    "HREF" TEXT NOT NULL,

    CONSTRAINT "News_pkey" PRIMARY KEY ("ID_NEWS")
);

-- CreateTable
CREATE TABLE "Player_Hisrory" (
    "PLAYER_ID" INTEGER NOT NULL,
    "RESULT" INTEGER NOT NULL,
    "MOD" TEXT NOT NULL,

    CONSTRAINT "Player_Hisrory_pkey" PRIMARY KEY ("PLAYER_ID")
);
