version: '3'

networks:
  client-server:
    driver: bridge
  server-database:
    driver: bridge
  databaseNet:
    driver: bridge

services:

  database:
    container_name: database
    image: postgres:16
    environment:
      POSTGRES_USER: rook_user
      POSTGRES_PASSWORD: rook_pass
      PGDATA: /data/postgres
    networks:
      - server-database
      - databaseNet
    ports:
      - "3002:5432"
    restart: unless-stopped

  databaseControl:
    container_name: databaseControl
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: rook@mail.com
      PGADMIN_DEFAULT_PASSWORD: rook_pass
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    networks:
      - databaseNet
    ports:
      - 127.0.0.1:3050:80
    restart: unless-stopped

  server:
    container_name: rook-server
    networks:
      - client-server
      - server-database
    build:
      context: chess_BE
    ports:
      - 127.0.0.1:3001:3001
    command: npm start

  client:
    container_name: rook-client
    networks:
      - client-server
    build:
      context: chess_FE
    ports:
      - 127.0.0.1:3000:3000
    command: npm start
    depends_on:
      - server
