-- CreateTable
CREATE TABLE "Player" (
    "ID_PLAYER" SERIAL NOT NULL,
    "USERNAME" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "PASSWORD" TEXT NOT NULL,
    "CREATEDATE" TIMESTAMP(3) NOT NULL,
    "CONFIRMED" BOOLEAN NOT NULL,
    "PERMISSIONS" TEXT NOT NULL,

    CONSTRAINT "Player_pkey" PRIMARY KEY ("ID_PLAYER")
);

-- CreateTable
CREATE TABLE "Game" (
    "ID_GAME" TEXT NOT NULL,
    "ID_PLAYER_1" INTEGER NOT NULL,
    "ID_PLAYER_2" INTEGER NOT NULL,
    "WINNER" INTEGER NOT NULL,
    "TURNS" TEXT NOT NULL,

    CONSTRAINT "Game_pkey" PRIMARY KEY ("ID_GAME")
);

-- CreateTable
CREATE TABLE "News" (
    "ID_NEWS" INTEGER NOT NULL,
    "ID_PLAYER" INTEGER NOT NULL,
    "TEXT" TEXT NOT NULL,
    "TITLE" TEXT NOT NULL,
    "HREF" TEXT NOT NULL,

    CONSTRAINT "News_pkey" PRIMARY KEY ("ID_NEWS")
);

-- CreateTable
CREATE TABLE "Learn" (
    "ID_LEARN" INTEGER NOT NULL,
    "TITLE" TEXT NOT NULL,
    "TEXT" TEXT NOT NULL,

    CONSTRAINT "Learn_pkey" PRIMARY KEY ("ID_LEARN")
);

-- CreateTable
CREATE TABLE "Player_History" (
    "PLAYER_ID" INTEGER NOT NULL,
    "RESULT" INTEGER NOT NULL,
    "MOD" TEXT NOT NULL,

    CONSTRAINT "Player_History_pkey" PRIMARY KEY ("PLAYER_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "Player_EMAIL_key" ON "Player"("EMAIL");
