-- CreateTable
CREATE TABLE "Player" (
    "ID_PLAYER" SERIAL NOT NULL,
    "USERNAME" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "PASSWORD" TEXT NOT NULL,
    "CREATEDATE" TIMESTAMP(3) NOT NULL,
    "CONFIRMED" BOOLEAN NOT NULL,

    CONSTRAINT "Player_pkey" PRIMARY KEY ("ID_PLAYER")
);
