FROM node:latest

WORKDIR /chess_BE/

# Копируем файлы package.json и package-lock.json и устанавливаем зависимости
COPY package.json package-lock.json ./
RUN npm install

# Копируем остальные файлы проекта
COPY . .
EXPOSE 3001

# Генерируем Prisma Client с указанными binaryTargets
RUN npx prisma generate

# Запускаем сервер
CMD npm run start:dev