-- CreateTable
CREATE TABLE "Player" (
    "ID_PLAYER" SERIAL NOT NULL,
    "USERNAME" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "PASSWORD" TEXT NOT NULL,
    "CREATEDATE" TIMESTAMP(3) NOT NULL,
    "CONFIRMED" BOOLEAN NOT NULL,
    "PERMISSIONS" TEXT NOT NULL,

    CONSTRAINT "Player_pkey" PRIMARY KEY ("ID_PLAYER")
);

-- CreateTable
CREATE TABLE "Game" (
    "ID_GAME" SERIAL NOT NULL,
    "PLAYER_1" TEXT NOT NULL DEFAULT '',
    "PLAYER_2" TEXT NOT NULL DEFAULT '',
    "WINNER" TEXT NOT NULL,
    "TURNS" TEXT NOT NULL,

    CONSTRAINT "Game_pkey" PRIMARY KEY ("ID_GAME")
);

-- CreateTable
CREATE TABLE "News" (
    "ID_NEWS" INTEGER NOT NULL,
    "ID_PLAYER" INTEGER NOT NULL,
    "TEXT" TEXT NOT NULL,
    "TITLE" TEXT NOT NULL,
    "HREF" TEXT NOT NULL,

    CONSTRAINT "News_pkey" PRIMARY KEY ("ID_NEWS")
);

-- CreateTable
CREATE TABLE "Learn" (
    "ID_LEARN" INTEGER NOT NULL,
    "TITLE" TEXT NOT NULL,
    "TEXT" TEXT NOT NULL,

    CONSTRAINT "Learn_pkey" PRIMARY KEY ("ID_LEARN")
);

-- CreateTable
CREATE TABLE "Player_History" (
    "PLAYER_ID" INTEGER NOT NULL,
    "RESULT" INTEGER NOT NULL,
    "MOD" TEXT NOT NULL,

    CONSTRAINT "Player_History_pkey" PRIMARY KEY ("PLAYER_ID")
);

-- CreateTable
CREATE TABLE "GameMods" (
    "MOD_ID" SERIAL NOT NULL,
    "MODE_NAME" TEXT NOT NULL,
    "TIME" INTEGER NOT NULL,
    "PLUS" INTEGER NOT NULL,

    CONSTRAINT "GameMods_pkey" PRIMARY KEY ("MOD_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "Player_EMAIL_key" ON "Player"("EMAIL");
