FROM node:latest

WORKDIR /chess_FE/
COPY package.json /chess_FE
COPY package-lock.json /chess_FE
COPY tsconfig.json /chess_FE
RUN npm install
COPY . .
RUN npm run build
EXPOSE 3000
CMD [«nginx», "-g", «daemon off;»]